### PR TITLE
TL_28 - Utility libraries - Datafaker, awaitility

### PR DESCRIPTION
**Pull request by verginia**
Added the information for this task in asciidoc format.

### CODE REVIEW

**Review by endalexei — APPROVED** [review]
Nicely done, great job Verginia

**Review by bodacd — APPROVED** [review]
Good job. Ready to be merged :)

**Comment by bodacd** [comment]
@verginia ,add please your name in the readmefile as author

**Comment by verginia** [comment]
added on the end, at the Copyright section

**Pull request merged**
